config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py --id 12b76f8e-d10e-4c5d-a113-4855f6bc3435 --plugin epos --repository
          https://www.ics-c.epos-eu.org/api/v1 --api-endpoint http://localhost:9090/v1.0/rda/rda_all
          --json
        container: qc.fair_scummy-gold-zonkey
timeout: 5400
